# Generated by Django 4.2.5 on 2023-10-01 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('university_id', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('uuid_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_dean', models.BooleanField(default=False)),
                ('is_student', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeansSessionAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_status', models.CharField(default='Free', max_length=10)),
                ('session_date', models.DateTimeField()),
                ('is_pending', models.BooleanField(default=True)),
                ('dean', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dean_availability', to='portal_api.customeuser')),
            ],
        ),
        migrations.CreateModel(
            name='StudentBookedSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_booked', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_session', to='portal_api.deanssessionavailability')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_sessions', to='portal_api.customeuser')),
            ],
        ),
    ]
